### ISSUE TITLE
Undocumented 0x0911 message type

### ISSUE THREAD

**Issue by redfast00** [BrandMeister/DigestPlay#1]
While debugging an unrelated issue, I noticed a client got 0x0911 (2343 in decimal) packets. These don't seem to be documented, what's in them? https://github.com/redfast00/brandmeister-dmr-opendmr/issues/1

**Comment by zarya** [comment]
REWIND_TYPE_DMR_DATA_BASE (0x910) + 1 is Voice Header (Full LC).
This is normal structure of DMR Voice Header, 12 bytes in length (ETSI TS 102 361-1). You can skip calculation of CRC.
